blog/urls.py
from django.urls import path

from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('list/', blog_list, name='list_post'),
    path('detail/<int:id>/',blog_detail, name='blog_detail'),
    path('create/',blog_create, name='blog_create'),
    path('create_using_form/',create_blog_using_django_form, name='blog_create_using_form'),
]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models

from django.utils import timezone

# create your models here
class Post(models.Model):
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    photo = models.ImageField(upload_to='blogs/%Y/%m/%d', blank=True, null=True) # blogs/file_name

    # def __str__(self):
    #     return self.title

blog/forms.py
from django import forms

from blog.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author', 'body', 'photo')


















    # def __init__(self, *args, **kwargs):
    #     super(PostForm, self).__init__(*args, **kwargs)
    #     for visible in self.visible_fields():
    #         visible.field.widget.attrs['class']='form-control'

blog/views.py
from datetime import datetime

from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from blog.forms import PostForm
from blog.models import Post


# model manager
# objects

def blog_list(request):
    from django.forms import formset_factory
    # ArticleFormSet = formset_factory(ArticleForm, extra=2)

    # http request
    post = Post.objects.all()
    num_vis = request.session.get('visit_count', 1)
    request.session['visit_count'] = num_vis + 1
    front_end_ma_patahune_data = {'post_table_ko_data': post, 'test_value': 1, 'num_visits': num_vis,
                                  # 'formset': ArticleFormSet(initial=[
                                  #     {
                                  #         'title': 'Django is now open source',
                                  #         'pub_date': datetime.now(),
                                  #     },
                                  # ])
                                  }
    return render(request, 'list.html', context=front_end_ma_patahune_data)


def blog_detail(request, id):
    post = Post.objects.get(pk=id)
    return render(request, 'details.html', context={'post': post})


def blog_create(request):
    # form = PostForm(instance=Post.objects.get(pk=17))
    # import pdb
    # pdb.set_trace()
    if request.method == 'POST':
        # f = PostForm(request.POST, request.FILES)
        # if f.is_valid():
        #     f.save()
        author = request.POST.get('author', request.user)
        if author:
            author_object = User.objects.get(username=author)
        title = request.POST.get('title', 'default title')
        body = request.POST.get('body', 'Content ContentContentContentContentContentContentContentContent')
        Post.objects.create(author=author_object, title=title, body=body, photo=request.FILES.get('photo'))
        # return render(request, 'list.html')
        return redirect(reverse('blog:list_post'))
    context = {'users': User.objects.all()}
    return render(request, 'create.html', context=context)


"""
static:
    js,
    css,
    image
    
    Static Root:
        --> The directory where we collect all of the static files in the system
    static Url:
        --> Url to set inorder to access the static files
    
    Static File directory:
        -->  Where we locally store the static files
        
        
    Media:
        --> 
"""


def create_blog_using_django_form(request):
    f = PostForm()
    if request.method == 'POST':
        f = PostForm(request.POST, request.FILES)
        valid_check = f.is_valid()
        if valid_check:
            f.save()
            return redirect(reverse('blog:list_post'))

    return render(request, 'create_post_django_form.html', context={'form': f})
    pass

blog/templates/create.html
<form method="post" action="{% url 'blog:blog_create' %}" enctype="multipart/form-data">
    {% csrf_token %}
{#    <table>#}
{#    {{ form.as_table }}#}
{#        </table>#}

    <label for="fname">Title:</label>
    <input type="text" id="fname" name="title"><br><br>
    <label for="lname">Author:</label>
    <select name="author" id="lname">
        {% for user in users %}
            <option value={{ user.username }}>{{ user }}</option>
        {% endfor %}
    </select><br><br>
    <label for="lname">Body:</label>
    <input type="text" id="lname" name="body"><br><br>
    <label for="fphoto">Photo</label>
    <input type="file" name="photo" id="fphoto">
    <input type="submit" value="Submit">
</form>

{{ users }}
{#OWASPP top 10:#}
{#1) CSRF (Cross site request forgery)#}

blog/templates/create_post_django_form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

blog/templates/list.html
{% load static %}
<link rel="stylesheet" href="{% static 'list.css' %}">
<h1>
    posts:
    {% for post in post_table_ko_data %}
        <br>
        <a href="{% url 'blog:blog_detail' post.id %}"> {{ post.title }} </a>
        <br>
        <br>
        <img src="{{ MEDIA_URL }}{{ post.photo }}"> {# {{ media_url }} -> media/blogs/pexels-photo-2486168.jpeg    post.photo --> blogs/pexels-photo-2486168.jpeg#}
        <br>
    {% endfor %}
    <br>title
    test: {{ test_value }}
    <br>
    {{ num_visits }}
    <br>

{#    <br>#}
{#    {% for forms in formset %}#}
{#        <table>#}
{#            {{ forms.as_table }}#}
{#        </table>#}
{#    {% endfor %}#}
</h1>

templates/details.html
<strong>Title</strong>: {{ post.title }}
<br>
<br>
<strong>Body</strong>: {{ post.body }}
<br>
<br>
<strong>Author</strong>: {{ post.author }}
<br>
<br>
<strong>Created:</strong> {{ post.created }}